# a program to find if the number is prime number or not
def is_it_prime(num):
    if (num <= 1):
        print("It is not a prime number.")
    elif num > 2:
        for i in range(2,num):
            if num%i == 0:
                print("It is not a prime number.")
                break
        else:
            print(num, " is a prime number.")

''' drawback of this code is whlie processing large numbers it will take a long time 
because it have to test all tha value but the code generated by chatGPT only have to go 
through the root+1 step of the number which is better approach.'''

def main():
    try:
        number = int(input("Enter the numer: "))
        is_it_prime(number)

    except ValueError:
        print("Please! enter a integer.")  


if __name__ == "__main__":
    main()


#         def is_prime(n):
#     """Return True if n is a prime number, else False."""
#     if n <= 1:
#         return False
#     if n == 2:
#         return True  # 2 is the only even prime number
#     if n % 2 == 0:
#         return False  # no other even number is prime
    
#     max_divisor = int(n**0.5) + 1  # we only need to test up to the square root of n
#     for d in range(3, max_divisor, 2):
#         if n % d == 0:
#             return False
#     return True

# # Example usage:
# number = 29
# print(f"{number} is prime: {is_prime(number)}")
